#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 12 12:50:19 2018

@author: mauricio
"""

import pods
import numpy as np
import scipy as sp
import mlai
from matplotlib import pyplot as plt
import teaching_plots as plot


max_basis = 5
basis = mlai.polynomial

data = pods.datasets.olympic_marathon_men()
x = data['X']
y = data['Y']

data_limits = [1892, 2020]
num_data = x.shape[0]

#x1 = x[0:5]
#y1 = y[0:5]
#data_limits = [1892, 1928]
#num_data = x1.shape[0]

#plot.rmse_fit(x, y, param_name='num_basis', param_range=(1, max_basis+1), 
#              model=mlai.LM, basis=basis, data_limits=data_limits, 
#              xlim=data_limits, objective_ylim=[0, 0.3])

#plot.holdout_fit(x, y, param_name='num_basis', 
#                 param_range=(1, max_basis+1), 
#                 model=mlai.LM, basis=basis, data_limits=data_limits,
#                 permute=False, objective_ylim=[0, 0.6], xlim=data_limits)

#plot.loo_fit(x, y, param_name='num_basis', param_range=(1, max_basis+1),  
#             model=mlai.LM, basis=basis, data_limits=data_limits, 
#             xlim=data_limits, objective_ylim=[0., 2.0], prefix='olympic_loo')

plot.cv_fit(x, y, param_name='num_basis', param_range=(1, max_basis+1),  
               model=mlai.LM, basis=basis, data_limits=data_limits,
               xlim=data_limits, objective_ylim=[0.,2.], num_parts=5)